import type { QuizChoiceQuestion } from '../../types'

export const TASHKENT_CITY_QUESTIONS: readonly QuizChoiceQuestion[] = [
	{
		kind: 'quiz_choice',
		id: 'tashkent-001',
		prompt: 'Какой рынок считается одним из главных символов старого Ташкента?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Chorsu%20Bazaar%20in%20Tashkent.jpg',
		imageAlt: 'Базар Чорсу в Ташкенте',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Chorsu_Bazaar_in_Tashkent.jpg',
		choices: [
			{ id: 'chorsu', label: 'Чорсу' },
			{ id: 'kuyluk', label: 'Куйлюк' },
			{ id: 'farhad', label: 'Фархадский' },
			{ id: 'askiya', label: 'Аския' },
		],
		correctChoiceId: 'chorsu',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-002',
		prompt: 'Какая станция метро находится рядом с базаром Чорсу?',
		choices: [
			{ id: 'chorsu', label: 'Чорсу' },
			{ id: 'oybek', label: 'Ойбек' },
			{ id: 'minor', label: 'Минор' },
			{ id: 'beruniy', label: 'Беруни' },
		],
		correctChoiceId: 'chorsu',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-003',
		prompt: 'Какой объект Ташкента известен как высокая телебашня?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Tashkent%20TV%20Tower%20174.jpg',
		imageAlt: 'Ташкентская телебашня',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Tashkent_TV_Tower_174.jpg',
		choices: [
			{ id: 'tv-tower', label: 'Ташкентская телебашня' },
			{ id: 'humo-arena', label: 'Humo Arena' },
			{ id: 'palace-forums', label: 'Дворец форумов' },
			{ id: 'state-circus', label: 'Государственный цирк' },
		],
		correctChoiceId: 'tv-tower',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-004',
		prompt: 'На какой площади стоит памятник Амиру Темуру?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Amir%20Temur%20Square.jpg',
		imageAlt: 'Площадь Амира Темура в Ташкенте',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Amir_Temur_Square.jpg',
		choices: [
			{ id: 'amir-temur-square', label: 'Площадь Амира Темура' },
			{ id: 'independence-square', label: 'Площадь Независимости' },
			{ id: 'chorsu-square', label: 'Площадь Чорсу' },
			{ id: 'friendship-square', label: 'Площадь Дружбы народов' },
		],
		correctChoiceId: 'amir-temur-square',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-005',
		prompt: 'Как по-узбекски обычно называют площадь Независимости?',
		choices: [
			{ id: 'mustaqillik', label: 'Мустакиллик майдони' },
			{ id: 'registan', label: 'Регистан' },
			{ id: 'shahriston', label: 'Шахристон' },
			{ id: 'navruz', label: 'Навруз майдони' },
		],
		correctChoiceId: 'mustaqillik',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-006',
		prompt: 'Какой комплекс в старом городе связан с Кораном халифа Усмана?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Hazrati%20Imam%20Mosque%20Interior.jpg',
		imageAlt: 'Интерьер мечети Хазрати Имам в Ташкенте',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Hazrati_Imam_Mosque_Interior.jpg',
		choices: [
			{ id: 'hazrati-imam', label: 'Хазрати Имам' },
			{ id: 'minor-mosque', label: 'Мечеть Минор' },
			{ id: 'kukeldash', label: 'Медресе Кукельдаш' },
			{ id: 'abdulkasim', label: 'Медресе Абдулкасым' },
		],
		correctChoiceId: 'hazrati-imam',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-007',
		prompt: 'Какая мечеть Ташкента известна белым фасадом и расположением у канала Анхор?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Minor%20Mosque%20Tashkent.jpg',
		imageAlt: 'Мечеть Минор в Ташкенте',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Minor_Mosque_Tashkent.jpg',
		choices: [
			{ id: 'minor-mosque', label: 'Мечеть Минор' },
			{ id: 'tilla-sheikh', label: 'Мечеть Тилля-Шейх' },
			{ id: 'namazgah', label: 'Намазгох' },
			{ id: 'juma', label: 'Джума-мечеть' },
		],
		correctChoiceId: 'minor-mosque',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-008',
		prompt: 'Какая станция метро известна космической тематикой в оформлении?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Kosmonavtlar%20Station%20of%20Tashkent%20Metro%206.jpg',
		imageAlt: 'Станция метро Космонавтлар в Ташкенте',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Kosmonavtlar_Station_of_Tashkent_Metro_6.jpg',
		choices: [
			{ id: 'kosmonavtlar', label: 'Космонавтлар' },
			{ id: 'pakhtakor', label: 'Пахтакор' },
			{ id: 'novza', label: 'Новза' },
			{ id: 'hamid-olimjon', label: 'Хамид Олимжон' },
		],
		correctChoiceId: 'kosmonavtlar',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-009',
		prompt: 'Какая пара станций образует известный переход между линиями метро в центре?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Alisher%20Navoiy%20station%20on%20Uzbekistan%20Line%20of%20Tashkent%20Metro%20in%20Tashkent%20Uzbekistan.jpg',
		imageAlt: 'Станция метро Алишер Навои в Ташкенте',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Alisher_Navoiy_station_on_Uzbekistan_Line_of_Tashkent_Metro_in_Tashkent_Uzbekistan.jpg',
		choices: [
			{ id: 'pakhtakor-alisher-navoi', label: 'Пахтакор и Алишер Навои' },
			{ id: 'minor-bodomzor', label: 'Минор и Бодомзор' },
			{ id: 'chorsu-gafur-gulyam', label: 'Чорсу и Гафур Гулям' },
			{ id: 'dustlik-mashinasozlar', label: 'Дустлик и Машинасозлар' },
		],
		correctChoiceId: 'pakhtakor-alisher-navoi',
		difficulty: 'hard',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-010',
		prompt: 'Как называется линия метро, на которой находится станция Чорсу?',
		choices: [
			{ id: 'uzbekistan-line', label: 'Узбекистанская линия' },
			{ id: 'chilanzar-line', label: 'Чиланзарская линия' },
			{ id: 'yunusabad-line', label: 'Юнусабадская линия' },
			{ id: 'circle-line', label: 'Кольцевая линия' },
		],
		correctChoiceId: 'uzbekistan-line',
		difficulty: 'hard',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-011',
		prompt: 'Какой из вариантов является районом города Ташкента?',
		choices: [
			{ id: 'yunusabad', label: 'Юнусабад' },
			{ id: 'chirchik', label: 'Чирчик' },
			{ id: 'yangiyul', label: 'Янгиюль' },
			{ id: 'parkent', label: 'Паркент' },
		],
		correctChoiceId: 'yunusabad',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-012',
		prompt: 'Какой район Ташкента был создан самым новым из перечисленных?',
		choices: [
			{ id: 'yangihayot', label: 'Янгихаёт' },
			{ id: 'chilanzar', label: 'Чиланзар' },
			{ id: 'mirobod', label: 'Мирабад' },
			{ id: 'uchtepa', label: 'Учтепа' },
		],
		correctChoiceId: 'yangihayot',
		difficulty: 'hard',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-013',
		prompt: 'Название какого района буквально связано с “тремя холмами”?',
		choices: [
			{ id: 'uchtepa', label: 'Учтепа' },
			{ id: 'olmazor', label: 'Алмазар' },
			{ id: 'bektemir', label: 'Бектемир' },
			{ id: 'sergeli', label: 'Сергели' },
		],
		correctChoiceId: 'uchtepa',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-014',
		prompt: 'Какой район носит имя великого астронома и правителя?',
		choices: [
			{ id: 'mirzo-ulugbek', label: 'Мирзо-Улугбекский район' },
			{ id: 'shaykhantahur', label: 'Шайхантахурский район' },
			{ id: 'yakkasaray', label: 'Яккасарайский район' },
			{ id: 'yashnobod', label: 'Яшнабадский район' },
		],
		correctChoiceId: 'mirzo-ulugbek',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-015',
		prompt: 'Какой район Ташкента по названию связан с яблоневым садом?',
		choices: [
			{ id: 'olmazor', label: 'Алмазар' },
			{ id: 'bektemir', label: 'Бектемир' },
			{ id: 'sergeli', label: 'Сергели' },
			{ id: 'mirobod', label: 'Мирабад' },
		],
		correctChoiceId: 'olmazor',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-016',
		prompt: 'Какой аэропорт обслуживает основные международные рейсы Ташкента?',
		choices: [
			{ id: 'tashkent-airport', label: 'Международный аэропорт Ташкент' },
			{ id: 'samarkand-airport', label: 'Аэропорт Самарканд' },
			{ id: 'namangan-airport', label: 'Аэропорт Наманган' },
			{ id: 'urgench-airport', label: 'Аэропорт Ургенч' },
		],
		correctChoiceId: 'tashkent-airport',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-017',
		prompt: 'Какой крупный спортивно-концертный комплекс находится в Ташкенте?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Humo%20Arena%20%28Tashkent%2C%20UZB%29%202019.jpg',
		imageAlt: 'Humo Arena в Ташкенте',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Humo_Arena_(Tashkent,_UZB)_2019.jpg',
		choices: [
			{ id: 'humo-arena', label: 'Humo Arena' },
			{ id: 'registan-arena', label: 'Registan Arena' },
			{ id: 'aral-palace', label: 'Aral Palace' },
			{ id: 'zarafshan-dome', label: 'Zarafshan Dome' },
		],
		correctChoiceId: 'humo-arena',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-018',
		prompt: 'Какой парк развлечений расположен рядом с центром Tashkent City?',
		choices: [
			{ id: 'magic-city', label: 'Magic City' },
			{ id: 'eco-park', label: 'Ecopark' },
			{ id: 'ankhor-lokomotiv', label: 'Анхор-Локомотив' },
			{ id: 'ashgabat-park', label: 'Парк Ашхабад' },
		],
		correctChoiceId: 'magic-city',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-019',
		prompt: 'Какой открытый музей в Ташкенте посвящён железнодорожной технике?',
		choices: [
			{ id: 'railway-museum', label: 'Музей железнодорожной техники' },
			{ id: 'art-museum', label: 'Музей искусств' },
			{ id: 'temurid-museum', label: 'Музей истории Темуридов' },
			{ id: 'polytechnic-museum', label: 'Политехнический музей' },
		],
		correctChoiceId: 'railway-museum',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-020',
		prompt: 'Какой музей находится рядом с площадью Амира Темура?',
		choices: [
			{ id: 'temurid-museum', label: 'Музей истории Темуридов' },
			{ id: 'savitsky-museum', label: 'Музей Савицкого' },
			{ id: 'afrosiab-museum', label: 'Музей Афросиаб' },
			{ id: 'khiva-museum', label: 'Музей Ичан-Кала' },
		],
		correctChoiceId: 'temurid-museum',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-021',
		prompt: 'Какой университет в Ташкенте известен английским названием WIUT?',
		choices: [
			{ id: 'wiut', label: 'Вестминстерский международный университет' },
			{ id: 'tsue', label: 'Ташкентский государственный экономический университет' },
			{ id: 'nuwu', label: 'Национальный университет Узбекистана' },
			{ id: 'inha', label: 'Университет Инха в Ташкенте' },
		],
		correctChoiceId: 'wiut',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-022',
		prompt: 'Какой университет носит имя Мирзо Улугбека?',
		choices: [
			{ id: 'national-university', label: 'Национальный университет Узбекистана' },
			{ id: 'world-economy', label: 'Университет мировой экономики и дипломатии' },
			{ id: 'medical-academy', label: 'Ташкентская медицинская академия' },
			{ id: 'architecture-university', label: 'Ташкентский архитектурно-строительный университет' },
		],
		correctChoiceId: 'national-university',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-023',
		prompt: 'Какой вуз в Ташкенте специализируется на мировой экономике и дипломатии?',
		choices: [
			{ id: 'uwed', label: 'УМЭД' },
			{ id: 'inha', label: 'Инха' },
			{ id: 'webster', label: 'Webster University' },
			{ id: 'tuit', label: 'ТУИТ' },
		],
		correctChoiceId: 'uwed',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-024',
		prompt: 'Какой университет чаще всего ассоциируется с ИТ и телекоммуникациями?',
		choices: [
			{ id: 'tuit', label: 'ТУИТ имени Мухаммада аль-Хорезми' },
			{ id: 'tslaw', label: 'Ташкентский государственный юридический университет' },
			{ id: 'conservatory', label: 'Государственная консерватория' },
			{ id: 'textile-institute', label: 'Текстильный институт' },
		],
		correctChoiceId: 'tuit',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-025',
		prompt: 'Какой общественный транспорт Ташкента знаменит художественно оформленными станциями?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Metro-Tashkent.jpg',
		imageAlt: 'Ташкентское метро',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Metro-Tashkent.jpg',
		choices: [
			{ id: 'metro', label: 'Метро' },
			{ id: 'tram', label: 'Трамвай' },
			{ id: 'funicular', label: 'Фуникулёр' },
			{ id: 'monorail', label: 'Монорельс' },
		],
		correctChoiceId: 'metro',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-026',
		prompt: 'Какая станция метро названа в честь дружбы народов?',
		choices: [
			{ id: 'xalqlar-dostligi', label: 'Халклар Дустлиги' },
			{ id: 'mustaqillik-maydoni', label: 'Мустакиллик майдони' },
			{ id: 'buyuk-ipak-yoli', label: 'Буюк Ипак Йули' },
			{ id: 'tinchlik', label: 'Тинчлик' },
		],
		correctChoiceId: 'xalqlar-dostligi',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-027',
		prompt: 'Какой парк Ташкента назван в честь столицы Туркменистана?',
		choices: [
			{ id: 'ashgabat-park', label: 'Парк Ашхабад' },
			{ id: 'seoul-park', label: 'Сеульский парк' },
			{ id: 'navoi-park', label: 'Парк Алишера Навои' },
			{ id: 'gafur-gulyam-park', label: 'Парк Гафура Гуляма' },
		],
		correctChoiceId: 'ashgabat-park',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-028',
		prompt: 'Какой парк Ташкента связан с южнокорейской тематикой?',
		choices: [
			{ id: 'seoul-park', label: 'Сеульский парк' },
			{ id: 'ashgabat-park', label: 'Парк Ашхабад' },
			{ id: 'eco-park', label: 'Ecopark' },
			{ id: 'botanical-garden', label: 'Ботанический сад' },
		],
		correctChoiceId: 'seoul-park',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-029',
		prompt: 'Какой район находится на северо-востоке города и дал название крупному жилому массиву?',
		choices: [
			{ id: 'yunusabad', label: 'Юнусабад' },
			{ id: 'chilanzar', label: 'Чиланзар' },
			{ id: 'sergeli', label: 'Сергели' },
			{ id: 'bektemir', label: 'Бектемир' },
		],
		correctChoiceId: 'yunusabad',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'tashkent-030',
		prompt: 'Какой объект Tashkent City чаще всего воспринимается как деловой центр нового формата?',
		choices: [
			{ id: 'business-center', label: 'Международный деловой центр' },
			{ id: 'railway-station', label: 'Северный вокзал' },
			{ id: 'botanical-garden', label: 'Ботанический сад' },
			{ id: 'chorsu-bazaar', label: 'Базар Чорсу' },
		],
		correctChoiceId: 'business-center',
		difficulty: 'easy',
	},
]
