import type { QuizChoiceQuestion } from '../../types'

export const UZBEKISTAN_GEOGRAPHY_QUESTIONS: readonly QuizChoiceQuestion[] = [
	{
		kind: 'quiz_choice',
		id: 'uz-geo-001',
		prompt: 'Какой город является столицей Узбекистана?',
		choices: [
			{ id: 'tashkent', label: 'Ташкент' },
			{ id: 'samarkand', label: 'Самарканд' },
			{ id: 'bukhara', label: 'Бухара' },
			{ id: 'namangan', label: 'Наманган' },
		],
		correctChoiceId: 'tashkent',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-002',
		prompt: 'В каком городе находится площадь Регистан?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Registan%20square%20%28Samarkand%29.jpg',
		imageAlt: 'Площадь Регистан в Самарканде',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Registan_square_(Samarkand).jpg',
		choices: [
			{ id: 'samarkand', label: 'Самарканд' },
			{ id: 'khiva', label: 'Хива' },
			{ id: 'nukus', label: 'Нукус' },
			{ id: 'andijan', label: 'Андижан' },
		],
		correctChoiceId: 'samarkand',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-003',
		prompt: 'Какое море сильно обмелело на территории Узбекистана и Казахстана?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Aral%20Sea%20%28aral-sea%29.jpg',
		imageAlt: 'Обмелевшее Аральское море',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Aral_Sea_(aral-sea).jpg',
		choices: [
			{ id: 'aral-sea', label: 'Аральское море' },
			{ id: 'caspian-sea', label: 'Каспийское море' },
			{ id: 'black-sea', label: 'Чёрное море' },
			{ id: 'red-sea', label: 'Красное море' },
		],
		correctChoiceId: 'aral-sea',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-004',
		prompt: 'Какая страна граничит с Узбекистаном на севере?',
		choices: [
			{ id: 'kazakhstan', label: 'Казахстан' },
			{ id: 'iran', label: 'Иран' },
			{ id: 'india', label: 'Индия' },
			{ id: 'china', label: 'Китай' },
		],
		correctChoiceId: 'kazakhstan',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-005',
		prompt: 'Какой город знаменит крепостью Ичан-Кала?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Itchan%20Kala%20Khiva%20World%20Heritage%20Site.jpg',
		imageAlt: 'Ичан-Кала в Хиве',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Itchan_Kala_Khiva_World_Heritage_Site.jpg',
		choices: [
			{ id: 'khiva', label: 'Хива' },
			{ id: 'termez', label: 'Термез' },
			{ id: 'karshi', label: 'Карши' },
			{ id: 'fergana', label: 'Фергана' },
		],
		correctChoiceId: 'khiva',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-006',
		prompt: 'Какая пустыня занимает большую часть северо-запада Узбекистана?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Kyzylkum%20Desert%20in%20Uzbekistan.jpg',
		imageAlt: 'Пустыня Кызылкум в Узбекистане',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Kyzylkum_Desert_in_Uzbekistan.jpg',
		choices: [
			{ id: 'kyzylkum', label: 'Кызылкум' },
			{ id: 'sahara', label: 'Сахара' },
			{ id: 'gobi', label: 'Гоби' },
			{ id: 'taklamakan', label: 'Такла-Макан' },
		],
		correctChoiceId: 'kyzylkum',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-007',
		prompt: 'Какая река является одной из двух главных рек Узбекистана?',
		choices: [
			{ id: 'amu-darya', label: 'Амударья' },
			{ id: 'volga', label: 'Волга' },
			{ id: 'nile', label: 'Нил' },
			{ id: 'danube', label: 'Дунай' },
		],
		correctChoiceId: 'amu-darya',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-008',
		prompt: 'Какая река связана с Ферганской долиной?',
		choices: [
			{ id: 'syr-darya', label: 'Сырдарья' },
			{ id: 'thames', label: 'Темза' },
			{ id: 'rhine', label: 'Рейн' },
			{ id: 'mekong', label: 'Меконг' },
		],
		correctChoiceId: 'syr-darya',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-009',
		prompt: 'Какой город является столицей Каракалпакстана?',
		choices: [
			{ id: 'nukus', label: 'Нукус' },
			{ id: 'urgench', label: 'Ургенч' },
			{ id: 'navoi', label: 'Навои' },
			{ id: 'jizzakh', label: 'Джизак' },
		],
		correctChoiceId: 'nukus',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-010',
		prompt: 'Какой город является административным центром Бухарской области?',
		choices: [
			{ id: 'bukhara', label: 'Бухара' },
			{ id: 'gulistan', label: 'Гулистан' },
			{ id: 'namangan', label: 'Наманган' },
			{ id: 'termiz', label: 'Термез' },
		],
		correctChoiceId: 'bukhara',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-011',
		prompt: 'В каком городе находится мавзолей Гур-Эмир?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Gur-e%20Amir%20in%20Samarkand%204.jpg',
		imageAlt: 'Мавзолей Гур-Эмир в Самарканде',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Gur-e_Amir_in_Samarkand_4.jpg',
		choices: [
			{ id: 'samarkand', label: 'Самарканд' },
			{ id: 'bukhara', label: 'Бухара' },
			{ id: 'khiva', label: 'Хива' },
			{ id: 'kokand', label: 'Коканд' },
		],
		correctChoiceId: 'samarkand',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-012',
		prompt: 'Какой город известен дворцом Худояр-хана?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Palace%20of%20Khudayar%20Khan.jpg',
		imageAlt: 'Дворец Худояр-хана в Коканде',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Palace_of_Khudayar_Khan.jpg',
		choices: [
			{ id: 'kokand', label: 'Коканд' },
			{ id: 'navoi', label: 'Навои' },
			{ id: 'muynak', label: 'Муйнак' },
			{ id: 'gulistan', label: 'Гулистан' },
		],
		correctChoiceId: 'kokand',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-013',
		prompt: 'Какой город традиционно ассоциируют с шёлком и ремёслами?',
		choices: [
			{ id: 'margilan', label: 'Маргилан' },
			{ id: 'zarafshan', label: 'Зарафшан' },
			{ id: 'muynak', label: 'Муйнак' },
			{ id: 'bekabad', label: 'Бекабад' },
		],
		correctChoiceId: 'margilan',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-014',
		prompt: 'В каком городе находится музей имени Савицкого?',
		choices: [
			{ id: 'nukus', label: 'Нукус' },
			{ id: 'khiva', label: 'Хива' },
			{ id: 'samarkand', label: 'Самарканд' },
			{ id: 'tashkent', label: 'Ташкент' },
		],
		correctChoiceId: 'nukus',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-015',
		prompt: 'С какой областью связан город Термез?',
		choices: [
			{ id: 'surkhandarya', label: 'Сурхандарьинская область' },
			{ id: 'sirdarya', label: 'Сырдарьинская область' },
			{ id: 'khorezm', label: 'Хорезмская область' },
			{ id: 'navoi', label: 'Навоийская область' },
		],
		correctChoiceId: 'surkhandarya',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-016',
		prompt: 'Какая страна находится к югу от Узбекистана?',
		choices: [
			{ id: 'afghanistan', label: 'Афганистан' },
			{ id: 'russia', label: 'Россия' },
			{ id: 'mongolia', label: 'Монголия' },
			{ id: 'azerbaijan', label: 'Азербайджан' },
		],
		correctChoiceId: 'afghanistan',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-017',
		prompt: 'Какая из этих стран НЕ граничит с Узбекистаном?',
		choices: [
			{ id: 'azerbaijan', label: 'Азербайджан' },
			{ id: 'tajikistan', label: 'Таджикистан' },
			{ id: 'turkmenistan', label: 'Туркменистан' },
			{ id: 'kyrgyzstan', label: 'Кыргызстан' },
		],
		correctChoiceId: 'azerbaijan',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-018',
		prompt: 'Какая горная система подходит к востоку Узбекистана?',
		choices: [
			{ id: 'tian-shan', label: 'Тянь-Шань' },
			{ id: 'alps', label: 'Альпы' },
			{ id: 'andes', label: 'Анды' },
			{ id: 'atlas', label: 'Атласские горы' },
		],
		correctChoiceId: 'tian-shan',
		difficulty: 'hard',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-019',
		prompt: 'Какая долина разделена между Узбекистаном, Кыргызстаном и Таджикистаном?',
		choices: [
			{ id: 'fergana-valley', label: 'Ферганская долина' },
			{ id: 'rift-valley', label: 'Великая рифтовая долина' },
			{ id: 'po-valley', label: 'Паданская долина' },
			{ id: 'loire-valley', label: 'Долина Луары' },
		],
		correctChoiceId: 'fergana-valley',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-020',
		prompt: 'Какой город был важной столицей Кокандского ханства?',
		choices: [
			{ id: 'kokand', label: 'Коканд' },
			{ id: 'zarafshan', label: 'Зарафшан' },
			{ id: 'chirchiq', label: 'Чирчик' },
			{ id: 'angren', label: 'Ангрен' },
		],
		correctChoiceId: 'kokand',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-021',
		prompt: 'Какой город является административным центром Хорезмской области?',
		choices: [
			{ id: 'urgench', label: 'Ургенч' },
			{ id: 'khiva', label: 'Хива' },
			{ id: 'nukus', label: 'Нукус' },
			{ id: 'bukhara', label: 'Бухара' },
		],
		correctChoiceId: 'urgench',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-022',
		prompt: 'Какой город является административным центром Кашкадарьинской области?',
		choices: [
			{ id: 'karshi', label: 'Карши' },
			{ id: 'termez', label: 'Термез' },
			{ id: 'navoi', label: 'Навои' },
			{ id: 'gulistan', label: 'Гулистан' },
		],
		correctChoiceId: 'karshi',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-023',
		prompt: 'Какой город является административным центром Сырдарьинской области?',
		choices: [
			{ id: 'gulistan', label: 'Гулистан' },
			{ id: 'jizzakh', label: 'Джизак' },
			{ id: 'namangan', label: 'Наманган' },
			{ id: 'urgench', label: 'Ургенч' },
		],
		correctChoiceId: 'gulistan',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-024',
		prompt: 'Какой город является административным центром Джизакской области?',
		choices: [
			{ id: 'jizzakh', label: 'Джизак' },
			{ id: 'andijan', label: 'Андижан' },
			{ id: 'bukhara', label: 'Бухара' },
			{ id: 'nukus', label: 'Нукус' },
		],
		correctChoiceId: 'jizzakh',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-025',
		prompt: 'С какой областью связан карьер Мурунтау, один из крупнейших золотых карьеров мира?',
		choices: [
			{ id: 'navoi', label: 'Навоийская область' },
			{ id: 'khorezm', label: 'Хорезмская область' },
			{ id: 'fergana', label: 'Ферганская область' },
			{ id: 'andijan', label: 'Андижанская область' },
		],
		correctChoiceId: 'navoi',
		difficulty: 'hard',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-026',
		prompt: 'Какой город является административным центром Наманганской области?',
		choices: [
			{ id: 'namangan', label: 'Наманган' },
			{ id: 'fergana', label: 'Фергана' },
			{ id: 'andijan', label: 'Андижан' },
			{ id: 'samarkand', label: 'Самарканд' },
		],
		correctChoiceId: 'namangan',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-027',
		prompt: 'Какая мечеть в Самарканде связана с именем Биби-Ханым?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Bibi-Khanym%20Mosque%2C%20Samarkand.jpg',
		imageAlt: 'Мечеть Биби-Ханым в Самарканде',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Bibi-Khanym_Mosque,_Samarkand.jpg',
		choices: [
			{ id: 'bibi-khanym', label: 'Мечеть Биби-Ханым' },
			{ id: 'minor', label: 'Мечеть Минор' },
			{ id: 'kalan', label: 'Мечеть Калян' },
			{ id: 'juma-khiva', label: 'Джума-мечеть Хивы' },
		],
		correctChoiceId: 'bibi-khanym',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-028',
		prompt: 'Какой город является административным центром Ташкентской области?',
		choices: [
			{ id: 'nurafshon', label: 'Нурафшон' },
			{ id: 'tashkent-city', label: 'город Ташкент' },
			{ id: 'chirchiq', label: 'Чирчик' },
			{ id: 'angren', label: 'Ангрен' },
		],
		correctChoiceId: 'nurafshon',
		difficulty: 'hard',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-029',
		prompt: 'Какая площадь является одной из центральных достопримечательностей Ташкента?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Amir%20Temur%20Square.jpg',
		imageAlt: 'Площадь Амира Темура в Ташкенте',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Amir_Temur_Square.jpg',
		choices: [
			{ id: 'amir-temur-square', label: 'Площадь Амира Темура' },
			{ id: 'registan-square', label: 'Регистан' },
			{ id: 'ichan-kala', label: 'Ичан-Кала' },
			{ id: 'ark-fortress', label: 'Крепость Арк' },
		],
		correctChoiceId: 'amir-temur-square',
		difficulty: 'easy',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-030',
		prompt: 'С каким городом связана крепость Арк?',
		choices: [
			{ id: 'bukhara', label: 'Бухара' },
			{ id: 'andijan', label: 'Андижан' },
			{ id: 'jizzakh', label: 'Джизак' },
			{ id: 'gulistan', label: 'Гулистан' },
		],
		correctChoiceId: 'bukhara',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-031',
		prompt: 'Как называется скоростной поезд, связывающий Ташкент, Самарканд и Бухару?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Hi-speed%20trains%20Afrosiyab%20%28Uzbekistan%29.JPG',
		imageAlt: 'Скоростной поезд Афросиаб',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Hi-speed_trains_Afrosiyab_(Uzbekistan).JPG',
		choices: [
			{ id: 'afrosiyob', label: 'Афросиаб' },
			{ id: 'orient-express', label: 'Восточный экспресс' },
			{ id: 'sapsan', label: 'Сапсан' },
			{ id: 'talgo-steppe', label: 'Степной экспресс' },
		],
		correctChoiceId: 'afrosiyob',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-032',
		prompt: 'Какой город часто называют «музеем под открытым небом» из-за исторического центра?',
		choices: [
			{ id: 'bukhara', label: 'Бухара' },
			{ id: 'angren', label: 'Ангрен' },
			{ id: 'bekabad', label: 'Бекабад' },
			{ id: 'gulistan', label: 'Гулистан' },
		],
		correctChoiceId: 'bukhara',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-033',
		prompt: 'Где находится комплекс Хазрати Имам?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Hazrati%20Imam%20Mosque%20Interior.jpg',
		imageAlt: 'Интерьер мечети Хазрати Имам в Ташкенте',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Hazrati_Imam_Mosque_Interior.jpg',
		choices: [
			{ id: 'tashkent', label: 'Ташкент' },
			{ id: 'samarkand', label: 'Самарканд' },
			{ id: 'khiva', label: 'Хива' },
			{ id: 'termez', label: 'Термез' },
		],
		correctChoiceId: 'tashkent',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-034',
		prompt: 'Какой объект рядом с Ташкентом известен как популярное горное водохранилище?',
		choices: [
			{ id: 'charvak', label: 'Чарвакское водохранилище' },
			{ id: 'aidarkul', label: 'Айдаркуль' },
			{ id: 'sarygamysh', label: 'Сарыкамыш' },
			{ id: 'aral-sea', label: 'Аральское море' },
		],
		correctChoiceId: 'charvak',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-035',
		prompt: 'Какой горный курорт рядом с Ташкентом часто связывают с Чимганом?',
		choices: [
			{ id: 'beldersay', label: 'Бельдерсай' },
			{ id: 'muynak', label: 'Муйнак' },
			{ id: 'zarafshan', label: 'Зарафшан' },
			{ id: 'gulistan', label: 'Гулистан' },
		],
		correctChoiceId: 'beldersay',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-036',
		prompt: 'Какой древний городище-музей находится в Самарканде?',
		choices: [
			{ id: 'afrosiab', label: 'Афросиаб' },
			{ id: 'ellikkala', label: 'Элликкала' },
			{ id: 'paikend', label: 'Пайкенд' },
			{ id: 'kampyrtepa', label: 'Кампыртепа' },
		],
		correctChoiceId: 'afrosiab',
		difficulty: 'hard',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-037',
		prompt: 'Какой город известен «кладбищем кораблей» у бывшего берега Арала?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Moynaq%20Aral-Sea%20Ships.jpg',
		imageAlt: 'Корабли у бывшего берега Аральского моря в Муйнаке',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Moynaq_Aral-Sea_Ships.jpg',
		choices: [
			{ id: 'muynak', label: 'Муйнак' },
			{ id: 'urgench', label: 'Ургенч' },
			{ id: 'nukus', label: 'Нукус' },
			{ id: 'karshi', label: 'Карши' },
		],
		correctChoiceId: 'muynak',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-038',
		prompt: 'Как называется известный минарет в историческом центре Бухары?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Kalyan%20Minaret%2C%20Bukhara.jpg',
		imageAlt: 'Минарет Калян в Бухаре',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Kalyan_Minaret,_Bukhara.jpg',
		choices: [
			{ id: 'kalan-minaret', label: 'Минарет Калян' },
			{ id: 'minor-minaret', label: 'Минарет Минор' },
			{ id: 'islam-khoja', label: 'Минарет Ислам-Ходжа' },
			{ id: 'qutlug-timur', label: 'Минарет Кутлуг-Тимур' },
		],
		correctChoiceId: 'kalan-minaret',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-039',
		prompt: 'В каком городе находится архитектурный ансамбль Ляби-Хауз?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Bukhara%2C%20around%20Lyabi-Hauz%20Square%20%286234994643%29.jpg',
		imageAlt: 'Ансамбль Ляби-Хауз в Бухаре',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Bukhara,_around_Lyabi-Hauz_Square_(6234994643).jpg',
		choices: [
			{ id: 'bukhara', label: 'Бухара' },
			{ id: 'samarkand', label: 'Самарканд' },
			{ id: 'tashkent', label: 'Ташкент' },
			{ id: 'andijan', label: 'Андижан' },
		],
		correctChoiceId: 'bukhara',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-040',
		prompt: 'Какой национальный парк находится в Джизакской области?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Zaamin%20National%20Park%2C%20Uzbekistan.jpg',
		imageAlt: 'Зааминский национальный парк',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Zaamin_National_Park,_Uzbekistan.jpg',
		choices: [
			{ id: 'zaamin', label: 'Зааминский национальный парк' },
			{ id: 'ugam-chatkal', label: 'Угам-Чаткальский парк' },
			{ id: 'baday-tugay', label: 'Бадай-Тугай' },
			{ id: 'hissar', label: 'Гиссарский заповедник' },
		],
		correctChoiceId: 'zaamin',
		difficulty: 'hard',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-041',
		prompt: 'Какой транспорт в Ташкенте был первым метрополитеном в Центральной Азии?',
		imageUrl:
			'https://commons.wikimedia.org/wiki/Special:FilePath/Metro-Tashkent.jpg',
		imageAlt: 'Ташкентское метро',
		imageCredit: 'Wikimedia Commons',
		imageCreditUrl:
			'https://commons.wikimedia.org/wiki/File:Metro-Tashkent.jpg',
		choices: [
			{ id: 'tashkent-metro', label: 'Ташкентский метрополитен' },
			{ id: 'tram', label: 'Ташкентский трамвай' },
			{ id: 'airport-express', label: 'Аэроэкспресс' },
			{ id: 'monorail', label: 'Монорельс' },
		],
		correctChoiceId: 'tashkent-metro',
		difficulty: 'medium',
	},
	{
		kind: 'quiz_choice',
		id: 'uz-geo-042',
		prompt: 'Как называют группу древних крепостей Каракалпакстана, включая Аяз-калу и Топрак-калу?',
		choices: [
			{ id: 'ellikkala', label: 'Элликкала' },
			{ id: 'registan', label: 'Регистан' },
			{ id: 'ichan-kala', label: 'Ичан-Кала' },
			{ id: 'hazrati-imam', label: 'Хазрати Имам' },
		],
		correctChoiceId: 'ellikkala',
		difficulty: 'hard',
	},
]
